name: Deploy Laravel API (Test & Production)

on:
  push:
    branches:
      - test # test
      - main # production
      - new-deploy # production

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    name: Deploy to Test Server
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, xml, zip

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Copy .env.test to .env
        run: cp .env.test .env

      - name: Deploy to Test Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/api/
          local-dir: ./
          exclude: |
            .git*
            .git/**
            .github/**
            node_modules/**
            tests/**
            storage/logs/**
            storage/framework/**
            .env*



  deploy-production:
    if: github.ref == 'refs/heads/new-deploy'
    runs-on: ubuntu-latest
    name: Deploy to Production Server
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, xml, zip

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # - name: Generate Swagger Docs
      #   run: php artisan l5-swagger:generate

      - name: Set Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Copy .env.production to .env
        run: cp .env.production .env

      - name: Deploy to Production Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME_LIVE }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /api/
          local-dir: ./
          exclude: |
            .git*
            .git/**
            .github/**
            node_modules/**
            tests/**
            storage/logs/**
            storage/framework/**
            .env*
            changes.sql



